# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_game', models.BooleanField(default=False)),
                ('game_code', models.CharField(max_length=5)),
                ('add_vampire', models.BooleanField(default=False)),
                ('add_cop', models.BooleanField(default=False)),
                ('round_num', models.IntegerField(default=1)),
                ('round_length', models.IntegerField(default=2)),
                ('mafia_num', models.IntegerField(default=1)),
                ('narrator_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=10)),
                ('creator', models.BooleanField(default=False)),
                ('in_game', models.BooleanField(default=False)),
                ('narrator', models.BooleanField(default=False)),
                ('vampire', models.BooleanField(default=False)),
                ('cop', models.BooleanField(default=False)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafiaapp.Game')),
            ],
        ),
    ]
